#testing
name: Code Quality and Tests
on:
  pull_request:
    branches:
      - develop
      - main
      - release/v*
      - hotfix/v*
  push:
    branches:
      - develop
      - master
      - release/v*
      - hotfix/v*

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements/local.txt

      - name: Check Code Formatting
        run: |
          black --check --config .black.cfg app/

      - name: Run Unit Tests
        run: |
          export PYTHONPATH=`pwd`
          pytest --cov=app tests/ --cov-config=.coveragerc --cov-report xml


      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: 46d3c6d311404a73bde290dcaad5c5e5
          coverage-reports: coverage.xml
