name: SYNC ROSTRA TESTING
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run workflow against'
        type: choice
        required: true
        options:
          - DEV
          - PROD2
          - PROD
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./profiles

jobs:
  dbt-dev-deployment:
    name: dbt dev Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Configure Deploy Environment
        run: |
          if ${{ github.ref == 'refs/heads/main' && github.event.inputs.environment == ''}}; then
            echo "SNOWFLAKE_ACCOUNT=${{ secrets.DEV_SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV;

          elif ${{ github.event.inputs.environment != '' }}; then
            echo "SNOWFLAKE_ACCOUNT=${{ secrets[format('{0}_SNOWFLAKE_ACCOUNT', github.event.inputs.environment)] }}" >> $GITHUB_ENV;
          else
              echo "Unknown Stage/Branch"
          fi

      - name: Running python file
        run: |
          echo "The value of AWS_ASSUME_ROLE is: $SNOWFLAKE_ACCOUNT"
