name: SYNC ROSTRA TESTING
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run workflow against'
        type: choice
        required: true
        options:
          - DEV
          - PROD2
          - PROD
  push:
    branches:
      - configure-runner

env:
  DBT_PROFILES_DIR: ./profiles

jobs:
  configure:
    name: configure
    runs-on: ubuntu-latest
    steps:
      - name: Set Runner Label
        id: set_runner
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "DEV" ]]; then
            echo "runner_label=windows-latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.environment }}" == "PROD2" ]]; then
            echo "runner_label=macos-latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.environment }}" == "PROD" ]]; then
            echo "runner_label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi
    outputs:
      runner_label: ${{ steps.set_runner.outputs.runner_label }}

  dbt-rostra-sync-push:
    name: dbt-rostra-sync-push
    needs: [configure]
    runs-on: ${{ needs.configure.outputs.runner_label }}
    if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        include:
          - environment: DEV
            runner_label: windows-latest
          - environment: PROD2
            runner_label: macos-latest
          - environment: PROD
            runner_label: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Configure Environment
        run: |

          if ${{ github.ref == 'refs/heads/main' }}; then
            echo "rostra_deployment_stage=${{ matrix.environment }}" >> $GITHUB_ENV;
          else
            echo "Unknown Stage/Branch"
          fi


     
  dbt-rostra-sync-dispatch:
    name: dbt-rostra-sync-dispatch
    needs: [configure]
    runs-on: ${{ needs.configure.outputs.runner_label }}
    if: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Configure Environment
        run: |

          if ${{ github.event.inputs.environment != '' }}; then
            echo "rostra_deployment_stage=${{github.event.inputs.environment}}" >> $GITHUB_ENV;
          else
            echo "Unknown Stage/Branch"
          fi

