name: SYNC ROSTRA TESTING
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run workflow against'
        type: choice
        required: true
        options:
          - DEV
          - PROD2
          - PROD
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./profiles

jobs:
  dbt-dev-deployment:
    name: dbt dev Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Configure Deploy Environment
        run: |

          if ${{ github.ref == 'refs/heads/main' && github.event.inputs.environment == ''}}; then
            echo "rostra_deployment_stage=dev" >> $GITHUB_ENV;
          elif ${{ github.event.inputs.environment != '' }}; then
            echo "rostra_deployment_stage=${{github.event.inputs.environment}}" >> $GITHUB_ENV;
          else
            echo "Unknown Stage/Branch"
          fi

      - name: Set SNOWFLAKE_ACCOUNT environment variable
        run: |
          echo "SNOWFLAKE_ACCOUNT=${{ secrets[env.rostra_deployment_stage + '_SNOWFLAKE_ACCOUNT'] }}" >> $GITHUB_ENV

      - name: Print SNOWFLAKE_ACCOUNT for debugging
        run: |
          echo "SNOWFLAKE_ACCOUNT=$SNOWFLAKE_ACCOUNT"

      - name: Running python file
        run: |
          python3 test.py
      
      # - name: setting env variables
      #   run: |
      #       stage = ${{ env.rostra_deployment_stage }}
      #       echo "SNOWFLAKE_ACCOUNT=${{ secrets[format('{0}_SNOWFLAKE_ACCOUNT', $rostra_deployment_stage )] }}" >> $GITHUB_ENV;


      # - name: Running python file
      #   run: |
      #     python3 test.py
