name: SYNC ROSTRA TESTING
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run workflow against'
        type: choice
        required: true
        options:
          - DEV
          - PROD2
          - PROD
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./profiles

jobs:
  dbt-dev-deployment:
    name: dbt dev Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Configure Deploy Environment
        run: |
          if ${{ github.ref == 'refs/heads/main' && github.event.inputs.environment == ''}}; then
            echo "SNOWFLAKE_ACCOUNT = ${{ secrets.DEV_SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV;

          elif ${{ github.event.inputs.environment }}; then
            echo "SNOWFLAKE_ACCOUNT = ${{ secrets[format('{0}_SNOWFLAKE_ACCOUNT', github.event.inputs.environment)] }}" >> $GITHUB_ENV;
          else
              echo "Unknown Stage/Branch"
          fi

      - name: print env variable
        run: |
          echo "Syncing with Snowflake account: $SNOWFLAKE_ACCOUNT"

          
      - name: Enforce Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dbt deps --target dev

      - name: Dbt Docs generate
        if: always()
        run: |
          dbt docs generate
          cd target
          ls -la

      - name: Sync Models, Macros & Test sqls between git and Rostra
        run: |
          python sync_git_with_rostra.py
